contact:
  email: patrick@covar.com
  name: Patrick Wang
  x-id: https://github.com/patrickkwang
  x-role: responsible developer
description: 'Answer coalesce: This serivce accepts a TRAPI 1.1 object containing answers and returns answers that have been coalesced by property, graph or ontology analysis.'
servers:
- description: Default server
  url: https://answercoalesce.renci.org
termsOfService: http://robokop.renci.org:7055/tos?service_long=Answer coalesce&provider_long=RENCI
title: Answer coalesce
tags:
- name: translator
- name: ARAGORN
- name: ARA
x-translator:
  component: ARA
  team:
  - Ranking Agent